services:
  db:
    container_name: auto-parts-finder-db
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "users_db"]
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - auto-parts-finder:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
      - ./init_data/data/vehicle_data.csv:/home/node/app/vehicle_data.csv
      - ./init_data/data/parts_with_compatibility.csv:/home/node/app/parts_with_compatibility.csv
  web:
    container_name: auto-parts-finder-web
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/app
    command: 'npm run testandrun'
volumes:
  auto-parts-finder:
  #make run on container not local