name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Reduced to one version since Docker will manage Node version

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    
    - name: Set up Docker Compose
      run: |
        # Make sure .env file exists with required values
        cd ProjectSourceCode
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=postgres" >> .env
        echo "POSTGRES_DB=users_db" >> .env
        echo "SESSION_SECRET=test_secret_for_github_actions" >> .env
        
    - name: Docker compose down and up
      run: |
        cd ProjectSourceCode
        docker-compose down -v || true # Continue even if this fails (if no containers exist yet)
        docker-compose up -d
        
    - name: Check container status
      run: |
        cd ProjectSourceCode
        docker-compose ps
        docker-compose logs
        
    - name: Wait for containers to be ready
      run: |
        cd ProjectSourceCode
        sleep 30  # Give more time for containers to initialize
        
    - name: Run tests in Docker
      run: |
        cd ProjectSourceCode
        # First try to execute using the testandrun script
        docker-compose exec -T web npm run testandrun || \
        # If that fails, try the direct test command
        docker-compose exec -T web npm test