name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]  # Reduced to one version since Docker will manage Node version

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: |
        # Make sure .env file exists with required values
        cd ProjectSourceCode
        echo "POSTGRES_USER=postgres" >> .env
        echo "POSTGRES_PASSWORD=postgres" >> .env
        echo "POSTGRES_DB=users_db" >> .env
        echo "SESSION_SECRET=test_secret_for_github_actions" >> .env
        
    - name: Docker compose up
      run: |
        cd ProjectSourceCode
        docker-compose up -d
        
    - name: Wait for containers to be ready
      run: |
        cd ProjectSourceCode
        sleep 10  # Give containers time to initialize
        
    - name: Run tests in Docker
      run: |
        cd ProjectSourceCode
        docker-compose exec -T web npm test